### ISSUE TITLE
Tests v Redis

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#1]
Any tests versus Redis planned for the near future?

**Comment by smoyergh** [comment]
We don't currently have plans to test versus Redis.  HSE targets data sets that greatly exceed DRAM capacity, whereas Redis is an in-memory DB.

The technologies are actually complementary.  For example, Redis enterprise has a feature Redis on Flash (RoF) that uses the RocksDB storage engine to support data sets larger than DRAM.  HSE could be used in a similar capacity for RoF.

**Comment by devinrsmith** [comment]
I'd be interested in comparisons vs LMDB for read speed (both random-access against unstructured key, and cursor read against all values).

**Comment by davidboles** [comment]
> I'd be interested in comparisons vs LMDB for read speed (both random-access against unstructured key, and cursor read against all values).

LMDB appears to have lots of great properties, many of which are shared with HSE (ordered map interface, fully-transactional, reader/writer transactions, extremely cheap read transactions, high concurrency, multiple sub-databases w/ transactions spanning them, self-recovering).

However, LMDB seems targeted at small to mid-size databases. HSE is targeted only at solid state media, is focused on large databases, and targets very low write-amp (no modify-in-place operations). Each domain has its own properties and presents distinct opportunities for optimization.

If you decide to write a benchmark that runs against both LMDB and HSE, the results would be most interesting if at least one of the modes would cover >=200M KV pairs with 1K values and measure ingest rate as well as the random access and cursor read rates and latencies, both with and without concurrent updates.

**Comment by smoyergh** [comment]
To emphasize one of the points made by @davidboles, HSE targets large datasets that exceed DRAM capacity.  We often test with datasets that are 8-64x DRAM size.
