### ISSUE TITLE
xxHash Upgrade

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#13]
Hey just wanted to call attention to the fact you all are using the old XXH32 and XXH64 hash functions which are slower than the new XXH3 one per the graph below (pulled from the xxHash github).

![image](https://user-images.githubusercontent.com/17534897/90301909-a12ce980-de70-11ea-9cab-bb16aec1f3a8.png)

**Comment by smoyergh** [comment]
Thanks for the pointer.  I logged an internal ticket and we'll look at this for a later release.  We're very close to releasing an update (with some really exciting new features!), but it's too late into our final testing to consider making this change right now.

**Comment by smoyergh** [comment]
HSE 1.9.0 upgraded to xxHash v0.8.0.  New KVSs created with HSE 1.9.0 use XXH3.
