### ISSUE TITLE
Stripesize Tuning

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#16]
> Disk striping is highly beneficial for applications with few users and large, sequential transfers. However, applications that exhibit small, concurrent, random I/O (such as databases) often see no performance gain through disk striping. Consider four disks with a stripe size of 512 bytes. Each 2K request is sent to all disks. One 2K request completes in about the same time when the disk has been striped. However, several 2K requests are all serialized because all the disks must seek for each request. On the nonstriped system, performance might actually be better because each disk might service separate requests in parallel. 

> If you plan to use the striped logical volume as a raw data partition (for example, for a database application that uses the device directly), the stripe size must be as large or larger than the I/O size for the application.

[https://docstore.mik.ua/manuals/hp-ux/en/5992-4589/ch02s04.html](https://docstore.mik.ua/manuals/hp-ux/en/5992-4589/ch02s04.html)

I saw the implicitly recommended stripesize on the [Configure Storage Wikipage](https://github.com/hse-project/hse/wiki/Configure-Storage) is `64K`. Was this explicitly chosen after performance testing?

And wondering if you have any general thoughts on the quotes above.

**Comment by smoyergh** [comment]
Yes, we tested various LVM stripesize values and found 64KB works best for a wide range of HSE workloads.  HSE aggregates data from puts, so the write I/O size seen by the drives does not correspond to KV pair value sizes.
