### ISSUE TITLE
Server Storage LVM configuration

### ISSUE THREAD

**Issue by eyylmaokai** [hse-project/hse#18]
Hello,
Regarding the server configuration for the YCSB performance results vs. MongoDB/WiredTiger, I wanted to ask a few questions regarding more details about the LVM configuration.

- Is the LVM built on top of Raid? If so what Raid type was used?
- What were the stripe configurations used such as stripe-size and data blocks per stripe, etc.

Thank you

**Comment by smoyergh** [comment]
The LVM was striped, no RAID.  The LVM stripesize was 64KB, and the SSD logical block size was 4KB, per best practices in the Configure Storage section of the Wiki.
