### ISSUE TITLE
Export KVDB from a LVM Snapshot for Zero Downtime Backups

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#24]
given that essentially while `hse_kvdb_export_exp()` is running all access to the kvdb must cease, what about snapshotting the logical volume that backs it, making the snapshot read-only, and then reopening the kvdb again from that snapshotted volume and conducting the serialization export that way? might that break something?

essentially i'm trying to design a way to export without needing to take my database offline.

**Comment by smoyergh** [comment]
You can snapshot the underlying volume and open it elsewhere.  But keep in mind that unless you quiesce the KVDB before taking the logical volume snapshot then you have a crash consistent backup.

**Comment by victorstewart** [comment]
@smoyergh how do I quiesce it?

my plan is to use datoobd, because then I don't have to take the source volume offline. (only just getting my bearings on all this stuff).

[https://github.com/datto/dattobd](https://github.com/datto/dattobd)

> Dattobd is a true live-snapshotting system that will leave your root volume running and available, without requiring a reboot.

> Create a snapshot:
> 
> dbdctl setup-snapshot /dev/sda1 /.datto 0
> 
> This will create a snapshot of the root volume at /dev/datto0

**Comment by victorstewart** [comment]
one problem with this that is surely remediable is that when i `hse_kvdb_open()` then it `mpool_open()`, currently there's no way to specify what device to find the mpool on... so one I create that snapshot clone... there's no way to differentiate which device I want it to read from.

but once that differentiation is possible, then this is simple to do. imagine...

```
// 0) sync all data to disk
   hse_kvdb_sync(DatabaseHub::database);

// 1) create snapshot with dattobd
   // will result in /dev/datto0 with a backing COW file at /.datto
   dattobd_setup_snapshot(0, "/dev/database_vg/database_lv", "/.datto", 0, 0);

   std::thread serializer( [] () {
      struct hse_kvdb *databaseClone;
      hse_kvdb_open("/dev/datto0", "database_mpool", NULL, &databaseClone);

      ...
   });
```

**Comment by victorstewart** [comment]
from rereading the mpool wiki page, I now get the idea that the mpool isn't anything actually written to the logical volume but just an interface to it that exists in the kernel, yes? 

and in that case i can simply create a new mpool with a new name ontop of the cloned logical volume, and then open the kvdb and all will work?

**Comment by smoyergh** [comment]
That approach won't work because mpool writes a superblock to each media class volume (which libblkid understands), and that superblock contains a UUID for the mpool.  So you cannot just give the snapshotted mpool volume a new name and use it.

Maybe this could be done with containers if the containers cannot see the same /dev entries, but we have never tried it so I cannot say for certain.

**Comment by victorstewart** [comment]
@smoyergh 

okay in the meantime i can stomach taking the database offline to clients while i run the serialization, (having not launched yet + data size will be small for a while).

there's no other way currently to open a copy-on-write clone of an mpool i presume?

but i think this would be a **hugely** value feature, and am willing to do all the necessary work on mpool to enable it once you begin accepting PRs.

**Comment by smoyergh** [comment]
As a policy we do not pre-announce HSE features or the exact timing of planned HSE releases.  That said, we have on our roadmap an mpool-related change that will support the use case you specify above.  We also have on our roadmap KVDB features that would allow you to accomplish the same goal in a different manner.

**Comment by smoyergh** [comment]
I don't think this is your use case, but a way to accomplish what you want with the current HSE release is with a SAN or other remote storage, since can snapshot the volume and then mount it on a different machine.

And do look into a container environment to see if you can isolate the RW/snapshot volumes in different containers.
