### ISSUE TITLE
Header Documentation Conflict

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#251]
### Description

the header comment for `hse_kvs_cursor_read` says...

>  If the argument @p val is NULL, only the key is read.

but also...

> @remark @p val must not be NULL.

### Steps to reproduce

N/A

### Linux Distribution

N/A

### File System

N/A

### Other System details

N/A

**Comment by tristan957** [comment]
The first comment is correct. The second comment is incorrect. Vestiges...

I don't think we will have another 2.1 series release, but I will go ahead and submit a PR to fix this for 3.0. We will be cleaning up the header documentation a bit before the next release: https://github.com/hse-project/hse/pull/165
