### ISSUE TITLE
SIGSEGV on hse_kvs_prefix_delete

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#260]
### Description

calling `hse_kvs_prefix_delete` like this...

hse_kvs_prefix_delete(db, 0, NULL, key, keySize);

with key == 5A:F9:60:12:C3:E3:A9:A4:12:C9:48:46:20:44:6B:BA:2E:64:65:76:69:63:65:41:72:6F:75:6E:64:73
and keySize == 30

and getting a SIGSEGV every single time across process runs regardless of the key input value (16 of those bytes are random and change on every run, the rest are static). always 30 bytes though. i can locate the exact line this is happening on inside the library tomorrow. but just FYI to open this issue.

using the latest release 2.1.1

the KVS was created with "pfx_len=16" if that matters.

### Linux Distribution

Clear Linux 5.17.4-1139.native

### File System

ext4

**Comment by tristan957** [comment]
A traceback would definitely be awesome if you could provide one. A minimally reproducible program would also be great if you could provide one.

Does just doing hse_kvs_prefix_delete() with the key you provided reproduce the error?

**Comment by alexttx** [comment]
If the KVS prefix length is 16, and your prefix key delete length is 30, you should be hitting this line of code in ikvdb.c:
```
    if (kt->kt_len != kk->kk_cparams->pfx_len)
        return merr(EINVAL);
```

**Comment by alexttx** [comment]
From https://hse-project.github.io/2.x/api/Modules/group__KVS/#function-hse_kvs_prefix_delete
> ... the caller passes a filter with a length equal to the KVSs key prefix length

The rules are:
- KVS prefix length must be less than or equal to `HSE_KVS_PFX_LEN_MAX`
- The filter used with prefix delete must equal the KVS prefix length
- Cursors can use a filter key of any length, but performance is dramatically reduced if filter len < KVS prefix length

**Comment by alexttx** [comment]
Prefix delete has had these restrictions since the initial release of HSE.  We have plans to eliminate these restrictions in a future release:  will not need to define KVSes with a prefix length, will support efficicent cursors with any filter length, and will replace prefix delete with a more general range delete.

**Comment by alexttx** [comment]
>  "rule" 2 isn't a rule because of 3?
rule 2 applies to prefix delete.  rule 3 applies to cursors.

> 3 implies performance is not reduced if the filter length is greater than pfx_len?
correct -- cursor performance is not reduced.

**Comment by alexttx** [comment]
also, please post a stack trace.  if there's a segv in HSE, we want to fix it.

**Comment by victorstewart** [comment]
@alexttx yes i'm going to debug it myself in a few minutes i'll post the bug once i find it.

oh okay i understand now. so i can just define my own prefix delete operation for now that uses cursors and individually deletes the keys.

and i see where my confusion comes from. in the header above prefix delete it says both 

> To do this the caller passes a filter with a length equal to the KVSs key prefix length

AND

> @remark @p pfx_len must be less than or equal to HSE_KVS_PFX_LEN_MAX.

so those statements are slightly conflicting.

**Comment by alexttx** [comment]
> so those statements are slightly conflicting.

i agree.  we'll fix that.   thanks for pointing it out!

**Comment by victorstewart** [comment]
turns out the SIGSEGV was due to some library file mismatches on my side. but glad we cleared up these prefix rules because i did have a bug in my program RE that!
