### ISSUE TITLE
Deleting a KVDB

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#27]
if a kvdb by the same name exists already in the mpool, does `hse_kvdb_make()` delete it and create a new one?

**Comment by tristan957** [comment]
No, you should get a non-zero `hse_err_t` representing `EEXIST`. You can use `hse_err_to_errno(hse_err_t)` to get the `errno` value from the `hse_err_t`.

**Comment by victorstewart** [comment]
@tristan957 then to delete a kvdb, is the only option to delete the mpool it's in?

**Comment by tristan957** [comment]
At least for right now, yes.
