### ISSUE TITLE
Explain engine architecture

### ISSUE THREAD

**Issue by gitspeaks** [hse-project/hse#3]
Please provide additional docs explaining the engine internal architecture with specific  focus on topics such as the data access algorithm,  why it is inherently better then btree for ssd’s , why the need for a new kernel module as apposed to using standard file syscalls using O_DIRECT.

Additionally, please provide high level code review for several key CRUD scenarios referencing key functions and structures

**Comment by sherlockwu** [comment]
Plus, it would be great if the team could clarify:
1) Is the standalone Mpool module who handles the management of heterogenous devices(say two layers of devices)?
2) If so, how does Mpool works in high level?

Thanks

**Comment by smoyergh** [comment]
We anticipate publishing an overview whitepaper, though I can't comment on the timing.

For HSE API usage examples, see the API documentation in [hse.h](https://github.com/hse-project/hse/blob/master/include/hse/hse.h), and the [sample](https://github.com/hse-project/hse/tree/master/samples)programs.

For mpool concepts see the mpool [wiki](https://github.com/hse-project/mpool/wiki).

**Comment by sherlockwu** [comment]
> We anticipate publishing an overview whitepaper, though I can't comment on the timing.
> 
> For HSE API usage examples, see the API documentation in [hse.h](https://github.com/hse-project/hse/blob/master/include/hse/hse.h), and the [sample](https://github.com/hse-project/hse/tree/master/samples) programs.
> 
> For mpool concepts see the mpool [wiki](https://github.com/hse-project/mpool/wiki).

Oh, I see, thanks!

**Comment by davidboles** [comment]
> Could you point to the documentation or code piece in HSE that related to how it decides which storage layer the "key-value" pair will goes to? Thanks

Where HSE places the key and value of a given instance of a KV pair is determined by the expected lifetime of each, how each is expected to be accessed, and the available media classes. Placement of key and value are independent and a given instance may migrate between media classes over time. This is all under the control of the hse/src/cn component.
