### ISSUE TITLE
Zstd Compression

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#30]
i saw in the Release Notes a mention towards compression, and that LZ4 is the only option.

thought you should check out Density as its compression rate is MUCH higher.

[https://github.com/centaurean/density](https://github.com/centaurean/density)

![image](https://user-images.githubusercontent.com/17534897/102104484-25df4280-3e26-11eb-9db4-d8da32266a81.png)

**Comment by victorstewart** [comment]
actually iterating through all the various compression inputs on [https://quixdb.github.io/squash-benchmark/](https://quixdb.github.io/squash-benchmark/) it's basically either lz4 or density leading depending on the input.

**Comment by victorstewart** [comment]
it seems Density has been archived, but ZSTD would be a great other choice

**Comment by tristan957** [comment]
Could you explain what some advantages are of zstd over lz4?
