### ISSUE TITLE
Leaned-Out Build Options

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#31]
can we get some parameters in the Makefile to specify build only a static library? right now we have to build a static and dynamic and the tests and the java interface, which require curl, nghttp2, and java libraries. bit of a nuisance if you **only** need `hse_kvdb_static-lib`.

**Comment by tristan957** [comment]
Hey again Victor. Work is on-going to improve the build system. I have put forth a proposal about various issues our current build system has. Currently working on a plan of attack for making the migration to the new build system. The future build system will be much more configurable or at least configurations will be much easier to discover.

**Comment by victorstewart** [comment]
the nghttp2 dependency of curl was giving me a nightmare with linking against the dynamic library... for some reason could never make it find the library. so i just disabled nghttp2 in the sub cmake file.

but at large, i think the distributed and many file build system is a but of a nightmare to swallow, especially how the first Makefile generates the real Makefiles. I toyed with creating my own extracted subset build system, but quickly abandoned the idea lol.

**Comment by tristan957** [comment]
I'll be sure to tag you in this issue when the new build system hits GitHub.

**Comment by tristan957** [comment]
@victorstewart the new build system hit the master branch fyi. Please let us know what troubles you run into with it. The master branch is kind of in a state of flux at the moment as the component we call c1 is being replaced. What this means is that in the event of some sort of failure HSE currently won't be able to recover lost data correctly.

**Comment by tristan957** [comment]
New build system has been removed from GitHub for the time being while we do some behind the scenes work around our repo management. It'll come back soon enough though.

**Comment by tristan957** [comment]
@victorstewart new build system is out once again. Would appreciate your feedback if you have any as we prep for 2.0.
