### ISSUE TITLE
Minimal Mpool Size

### ISSUE THREAD

**Issue by victorstewart** [hse-project/hse#33]
i'm playing around with some testing, created a logical volume that's 3GB. Then created an mpool, then tried to create a KVDB but got no space left on device?

Also noticed how simply creating the mpool consumed 1.16GB. So I assume that's the baseline overhead of any mpool? and that a kvdb has a similar >1.22GB overhead?

didn't see these stats mentioned anywhere on the wiki so just curious as to the baseline overheads for mpool, kvdb and each kvs... and thus the minimal sized logical volume.

```
root@clr-a0be12ca44e34faf8d5303631473136b~/.../bin # mpool create hotmpool /dev/hotvg/hotlv
root@clr-a0be12ca44e34faf8d5303631473136b~/.../bin # mpool list
MPOOL      TOTAL    USED   AVAIL  CAPACITY  LABEL    HEALTH
hotmpool   2.50g   1.16g   1.22g    48.68%    raw   optimal
root@clr-a0be12ca44e34faf8d5303631473136b~/.../bin # ./hse kvdb create "hotmpool"
hse kvdb create: error from hse_kvdb_make: mpool/mpctl.c:142: No space left on device
```

**Comment by victorstewart** [comment]
then after i opened the KVDB, and created and opened 3 KVSs, before storing anything the usage grew to...

```
MPOOL      TOTAL    USED   AVAIL  CAPACITY  LABEL    HEALTH
hotmpool     29g     13g     14g    47.56%    raw   optimal
```

**Comment by smoyergh** [comment]
Yes, you're seeing preallocation of capacity for metadata and logging.  We actually scale those containers, but the lower bound is sized for a 1TB+ KVDB for historical reasons.

This will be eliminated in a future release of HSE which will not have a kernel module.
