### ISSUE TITLE
Dev mailing list

### ISSUE THREAD

**Issue by devinrsmith** [hse-project/hse#6]
Firstly, I'm glad that hse has documentation around best practices for thinking about and structuring keys - it's a subject that seems to be sorely missing in the world of embedded KV databases.

Secondly, is there any official means of communication with the hse-project outside of github issues? Potentially a public developer mailing list?

Cheers!

**Comment by smoyergh** [comment]
There is a pointer to the mailing list on the "Resources" page of the "Get Help" section of the Wiki.

**Comment by devinrsmith** [comment]
Do'h! Thanks :D
