### ISSUE TITLE
Could you support object with size more than 1 MB?

### ISSUE THREAD

**Issue by jliang000** [hse-project/hse#7]
1MB might be small for object storage. by split and merge introduce the complexity of the key management, for example, to list the key or object iteration.

**Comment by smoyergh** [comment]
We may support larger values in a later release, but unless we support unlimited value size, then for any size N there will be someone needing size N+1.

Can you provide more information on how you plan to iterate?  From that we can propose some design patterns that could work well for you.  Hopefully you've had the opportunity to read with **Concepts** and **Best Practices** sections of the Wiki, which provide information on how to achieve the best performance with iteration.

**Comment by jliang000** [comment]
understand. thanks
